const provinceList = [
  "- Select -",
    "Anhui Sheng",
    "Macau",
    "Beijing Shi",
    "Chongqing Shi",
    "Fujian Sheng",
    "Gansu Sheng",
    "Guangdong Sheng",
    "Guangxi Zhuangzuzizhiqu",
    "Guizhou Sheng",
    "Hainan Sheng",
    "Hebei Sheng",
    "Henan Sheng",
    "Heilongjiang Sheng",
    "Hubei Sheng",
    "Hunan Sheng",
    "Jilin Sheng",
    "Jiangsu Sheng",
    "Jiangxi Sheng",
    "Liaoning Sheng",
    "Neimenggu Zizhiqu",
    "Ningxia Huizuzizhiqu",
    "Qinghai Sheng",
    "Shandong Sheng",
    "Shanxi Sheng",
    "Shaanxi Sheng",
    "Shanghai Shi",
    "Sichuan Sheng",
    "Taiwan",
    "Tianjin Shi",
    "Xizang Zizhiqu",
    "Hong Kong",
    "Xinjiang Weiwuerzizhiqu",
    "Yunnan Sheng",
    "Zhejiang Sheng"
];

export {provinceList};