const regionList = [
  "- Select -",
    "Altayskiy kray",
    "Amurskaya oblast'",
    "Arkhangelskaya oblast'",
    "Astrakhanskaya oblast'",
    "Belgorodskaya oblast'",
    "Bryanskaya oblast'",
    "Vladimirskaya oblast'",
    "Volgogradskaya oblast'",
    "Vologodskaya oblast'",
    "Voronezhskaya oblast'",
    "Evreyskaya avtonomnaya oblast'",
    "Zabaykalskiy kray",
    "Ivanovskaya oblast'",
    "Irkutskaya oblast'",
    "Kabardino-Balkarskaya Republits",
    "Kaliningradskaya oblast'",
    "Kaluzhskaya oblast'",
    "Kamchatskiy kray",
    "Karachaevo-Cherkesskaya Republits",
    "Kemerovskaya oblast'",
    "Kirovskaya oblast'",
    "Kostromskaya oblast'",
    "Krasnodarskiy kray",
    "Krasnoyarskiy kray",
    "Kurganskaya oblast'",
    "Kurskaya oblast'",
    "Leningradskaya oblast'",
    "Lipetskaya oblast'",
    "Magadanskaya oblast'",
    "Moskva",
    "Moskovskaya oblast'",
    "Murmanskaya oblast'",
    "Nenetskiy",
    "Nizhegorodskaya oblast'",
    "Novgorodskaya oblast'",
    "Novosibirskaya oblast'",
    "Omskaya oblast'",
    "Orenburgskaya oblast'",
    "Orlovskaya oblast'",
    "Penzenskaya oblast'",
    "Permskiy kray",
    "Primorskiy kray",
    "Pskovskaya oblast'",
    "Respublika Adygeya",
    "Altay Republits",
    "Bashkortostan Republits",
    "Buryatiya Republits",
    "Dagestan Republits",
    "Ingushetiya Republits",
    "Respublika Kalmykiya",
    "Kareliya Republits",
    "Komi Republits",
    "Respublika Krym",
    "Respublika Mariy El",
    "Respublika Mordoviya",
    "Sakha (Yakutiya) Republits",
    "Respublika Severnaya Osetiya-Alaniya",
    "Respublika Tatarstan",
    "Tyva Republits",
    "Udmurtskaja Respublika",
    "Khakasiya Republits",
    "Rostovskaya oblast'",
    "Ryazanskaya oblast'",
    "Samarskaya oblast'",
    "Sankt-Peterburg",
    "Saratovskaya oblast'",
    "Sakhalinskaya oblast'",
    "Sverdlovskaya oblast'",
    "Sevastopol'",
    "Smolenskaya oblast'",
    "Stavropolskiy kray",
    "Tambovskaya oblast'",
    "Tverskaya oblast'",
    "Tomskaya oblast'",
    "Tulskaya oblast'",
    "Tyumenskaya oblast'",
    "Ulyanovskaya oblast'",
    "Khabarovskiy kray",
    "Khanty-Mansiyskiy avtonomnyy okrug",
    "Chelyabinskaya oblast'",
    "Chechenskaya Republits",
    "Chuvashia",
    "Chukotskiy",
    "Yamalo-Nenetskiy",
    "Yaroslavskaya oblast'"
];


export {regionList};