const provinceList = [
  "- Select -",
    "Krabi",
    "Bangkok",
    "Kanchanaburi",
    "Kalasin",
    "Kamphaeng Phet",
    "Khon Kaen",
    "Bueng Kan",
    "Chanthaburi",
    "Chachoengsao",
    "Chon Buri",
    "Chai Nat",
    "Chaiyaphum",
    "Chumpon",
    "Chiang Rai",
    "Chiang Mai",
    "Trang",
    "Trat",
    "Tak",
    "Nakhon Nayok",
    "Nakhon Pathom",
    "Nakhon Phanom",
    "Nakhon Ratchasima",
    "Nakhon Si Thammarat",
    "Nakhon Sawan",
    "Nonthaburi",
    "Narathiwat",
    "Nan",
    "Buri Ram",
    "Pathum Thani",
    "Prachuap Khiri Khan",
    "Prachin Buri",
    "Pattani",
    "Phra Nakhon Si Ayutthaya",
    "Phayao",
    "Phang Nga",
    "Phattalung",
    "Phichit",
    "Phitsanulok",
    "Phetchaburi",
    "Phetchabun",
    "Phrae",
    "Phuket",
    "Maha Sarakham",
    "Mukdahan",
    "Mae Hong Son",
    "Yasothon",
    "Yala",
    "Roi Et",
    "Ranong",
    "Rayong",
    "Ratchaburi",
    "Lop Buri",
    "Lampang",
    "Lamphun",
    "Loei",
    "Si Sa Ket",
    "Sakon Nakhon",
    "Songkhla",
    "Satun",
    "Samut Prakan",
    "Samut Songkhram",
    "Samut Sakhon",
    "Sa Kaeo",
    "Saraburi",
    "Sing Buri",
    "Sukhothai",
    "Suphanburi",
    "Surat Thani",
    "Surin",
    "Nong Khai",
    "Nong Bua Lam Phu",
    "Ang Thong",
    "Amnat Charoen",
    "Udon Thani",
    "Uttaradit",
    "Uthai Thani",
    "Ubon Ratchathani"
];


export {provinceList};